#!/usr/bin/env bash
# Radio-TTY one-shot setup — run once from the repo root, then:
#   docker compose up --build
#
# What this does:
#   1. Verifies Docker is available
#   2. Creates data/, Voices/, Models/ directories
#   3. Seeds data/config.json from the example (if missing)
#   4. Writes .env with your PulseAudio UID and compute backend
#   5. Downloads the Whisper STT model (small.en by default)
#   6. Downloads the 8 default Piper TTS voices
#
# Usage:
#   bash setup.sh                   # Whisper small.en + all voices (recommended)
#   bash setup.sh --model base.en   # smaller/faster Whisper (~145 MB)
#   bash setup.sh --model medium.en # higher-accuracy Whisper (~1.5 GB)
#   bash setup.sh --voice-only      # re-run voices only (skip Whisper)
#   bash setup.sh --skip-voices     # Whisper only (skip voices)

set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────

WHISPER_MODEL="small.en"
VOICE_ONLY=false
SKIP_VOICES=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)
      [[ $# -lt 2 ]] && { echo "Error: --model requires a value." >&2; exit 1; }
      WHISPER_MODEL="$2"; shift 2 ;;
    --voice-only)  VOICE_ONLY=true;  shift ;;
    --skip-voices) SKIP_VOICES=true; shift ;;
    -h|--help) sed -n '2,19p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $1  (try --help)" >&2; exit 1 ;;
  esac
done

case "$WHISPER_MODEL" in
  tiny.en)   REPO_ID="Systran/faster-whisper-tiny.en";   MODEL_SIZE="~75 MB"  ;;
  base.en)   REPO_ID="Systran/faster-whisper-base.en";   MODEL_SIZE="~145 MB" ;;
  small.en)  REPO_ID="Systran/faster-whisper-small.en";  MODEL_SIZE="~464 MB" ;;
  medium.en) REPO_ID="Systran/faster-whisper-medium.en"; MODEL_SIZE="~1.5 GB" ;;
  large-v3)  REPO_ID="Systran/faster-whisper-large-v3";  MODEL_SIZE="~3 GB"   ;;
  *)
    echo "Error: unknown model '$WHISPER_MODEL'." >&2
    echo "Valid choices: tiny.en  base.en  small.en  medium.en  large-v3" >&2
    exit 1 ;;
esac

HF_BASE="https://huggingface.co/rhasspy/piper-voices/resolve/main"

VOICES=(
  "en_US-ryan-high|en/en_US/ryan/high/en_US-ryan-high"
  "en_US-amy-medium|en/en_US/amy/medium/en_US-amy-medium"
  "en_US-arctic-medium|en/en_US/arctic/medium/en_US-arctic-medium"
  "en_US-hfc_female-medium|en/en_US/hfc_female/medium/en_US-hfc_female-medium"
  "en_US-kathleen-low|en/en_US/kathleen/low/en_US-kathleen-low"
  "en_US-kristin-medium|en/en_US/kristin/medium/en_US-kristin-medium"
  "en_US-lessac-high|en/en_US/lessac/high/en_US-lessac-high"
  "en_US-libritts-high|en/en_US/libritts/high/en_US-libritts-high"
)

# ── Guard: must be run from the repo root ─────────────────────────────────────

if [[ ! -f "backend/requirements.txt" ]]; then
  echo "Error: run this script from the Radio-TTY repo root." >&2
  echo "  cd /path/to/Radio-TTY && bash setup.sh" >&2
  exit 1
fi

# ── Guard: Docker must be available ──────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "Error: docker not found in PATH." >&2
  echo "Install Docker: https://docs.docker.com/engine/install/" >&2
  exit 1
fi

if ! docker info &>/dev/null; then
  echo "Error: Docker daemon is not running or you lack permission." >&2
  echo "Start Docker and/or add yourself to the 'docker' group, then re-run." >&2
  exit 1
fi

# ── 1. Local directories ──────────────────────────────────────────────────────

echo "==> Creating directories..."
mkdir -p data/journals data/public
mkdir -p Voices
mkdir -p "Models/STT"
echo "  data/  Voices/  Models/  — OK"

# ── 2. Seed config ────────────────────────────────────────────────────────────

echo ""
if [[ ! -f "data/config.json" ]]; then
  if [[ -f "data/config.json.example" ]]; then
    cp data/config.json.example data/config.json
    echo "==> Seeded data/config.json — remember to set your callsign:"
    echo "      nano data/config.json    (change \"callsign\": \"N0CALL\")"
  else
    echo "==> Warning: data/config.json.example not found." >&2
    echo "    Create data/config.json manually before starting the stack." >&2
  fi
else
  echo "==> data/config.json already exists, skipping seed."
fi

# ── 3. .env file ──────────────────────────────────────────────────────────────

echo ""
PULSE_UID="$(id -u)"

if [[ -f ".env" ]]; then
  if grep -q "^PULSE_UID=" .env; then
    sed -i "s|^PULSE_UID=.*|PULSE_UID=${PULSE_UID}|" .env
    echo "==> .env: updated PULSE_UID=${PULSE_UID}"
  else
    printf '\nPULSE_UID=%s\n' "$PULSE_UID" >> .env
    echo "==> .env: appended PULSE_UID=${PULSE_UID}"
  fi
else
  cat > .env <<EOF
# Radio-TTY Docker Compose environment — generated by setup.sh
# Re-run setup.sh to regenerate, or edit manually.

# Your Linux user ID — used to locate the PulseAudio socket at /run/user/<UID>/pulse
# Run 'id -u' to verify. Change if you deploy as a different user.
PULSE_UID=${PULSE_UID}

# Whisper hardware backend: cpu (default) | cuda | openvino
# Set to 'cuda' if the host has an NVIDIA GPU with the Container Toolkit installed.
COMPUTE_BACKEND=cpu
EOF
  echo "==> .env created (PULSE_UID=${PULSE_UID})"
fi

# ── 4. Whisper STT model ──────────────────────────────────────────────────────

if ! $VOICE_ONLY; then
  echo ""
  TARGET="Models/STT/${WHISPER_MODEL}"
  if [[ -d "$TARGET" ]] && [[ -n "$(ls -A "$TARGET" 2>/dev/null)" ]]; then
    echo "==> Whisper ${WHISPER_MODEL}: already present, skipping."
  else
    echo "==> Downloading Whisper ${WHISPER_MODEL} (${MODEL_SIZE}) — this may take a while..."
    mkdir -p "$TARGET"
    docker run --rm \
      -v "$(pwd)/Models:/models" \
      python:3.13-slim \
      bash -c "pip install -q --root-user-action=ignore huggingface_hub && python3 -c \"
import os
from huggingface_hub import snapshot_download
os.makedirs('/models/STT/${WHISPER_MODEL}', exist_ok=True)
snapshot_download('${REPO_ID}', local_dir='/models/STT/${WHISPER_MODEL}')
print('  Whisper ${WHISPER_MODEL} download complete.')
\""
    echo "  Saved to ${TARGET}/"
  fi
fi

# ── 5. Piper TTS voices ───────────────────────────────────────────────────────

if ! $SKIP_VOICES; then
  echo ""
  echo "==> Piper TTS voices..."
  VOICE_SCRIPT=""
  for entry in "${VOICES[@]}"; do
    stem="${entry%%|*}"
    hf_path="${entry##*|}"
    for ext in ".onnx" ".onnx.json"; do
      filename="${stem}${ext}"
      url="${HF_BASE}/${hf_path}${ext}"
      VOICE_SCRIPT+="
if [ -f '/v/${filename}' ]; then
  echo '  ${filename} — already present'
else
  echo '  Downloading ${filename}...'
  wget -q -O '/v/${filename}' '${url}' \
    && echo '  ${filename} — done' \
    || { echo '  FAILED: ${filename}' >&2; rm -f '/v/${filename}'; }
fi"
    done
  done
  docker run --rm -v "$(pwd)/Voices:/v" alpine sh -c "$VOICE_SCRIPT"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup complete."
echo ""
if grep -q '"callsign": "N0CALL"' data/config.json 2>/dev/null; then
  echo "  NEXT: edit data/config.json and change your callsign from N0CALL."
  echo "        nano data/config.json"
  echo ""
fi
echo "  Then start the stack:"
echo "        docker compose up --build"
echo ""
echo "  Open http://localhost in your browser once both containers are healthy."
echo "  On first visit you'll be prompted to create the admin account."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
